Test github action

diff --git a/.github/workflows/master-build-deploy-azure-aws.yml b/.github/workflows/master-build-deploy-azure-aws.yml
--- a/.github/workflows/master-build-deploy-azure-aws.yml
+++ b/.github/workflows/master-build-deploy-azure-aws.yml
@@ -1,9 +1,9 @@
-name: Build and Deploy React and ASP.NET Core App
+name: ApiLogix - AWS - Build and Deploy
 
 on:
   push:
     branches:
-      - master 
+      - master
   workflow_dispatch:
 
 jobs:
@@ -14,12 +14,34 @@ jobs:
       - name: Checkout code from develop branch
         uses: actions/checkout@v4
         with:
-          ref: master 
+          ref: master
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "18.x" # Specify the Node.js version you need
+
+      - name: Run Nextjs npm script
+        run: |
+          cd apilogix-react-app
+          npm install     
+          npm run testJunit
+          npm run build
+
+      - name: Test Jest Junit Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: JEST Tests # Name of the check run which will be created
+          path: "**/jest-*.xml" # Path to test results
+          reporter: jest-junit # Format of test results
+          fail-on-error: true
+          token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Set up .NET Core
         uses: actions/setup-dotnet@v1
         with:
-          dotnet-version: '8.x'
+          dotnet-version: "8.x"
           include-prerelease: true
 
       - name: Build with dotnet
@@ -38,14 +60,14 @@ jobs:
         with:
           name: net-app
           path: ${{ github.workspace }}/publish
-          retention-days: 1  # Retain for 1 day
+          retention-days: 1 # Retain for 1 day
 
   deploy-aws:
     runs-on: ubuntu-latest
-    needs: build  # This ensures that the deploy job waits for the build job to complete
-    if: ${{ success() }}  # Only run if the build job was successful
+    needs: build # This ensures that the deploy job waits for the build job to complete
+    if: ${{ success() }} # Only run if the build job was successful
     environment:
-      name: 'Production'
+      name: "Production"
 
     steps:
       - name: Download artifact from build job
@@ -73,9 +95,9 @@ jobs:
           PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           HOSTNAME: ${{secrets.EC2_HOST}}
           USER_NAME: ubuntu
-          
+
           run: |
             echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
             ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
               sudo systemctl restart apilogix-api.service
-              sudo systemctl reload nginx       
+              sudo systemctl reload nginx
